import React, { useState } from "react";
import { FaAppleAlt, FaClock, FaFire, FaUtensils, FaShoppingCart, FaLightbulb, FaChevronDown, FaChevronUp, FaCheck, FaCalendarAlt } from "react-icons/fa";

export default function DynamicDietPlanDisplay({ dietPlan, userInfo }) {
  const [expandedDay, setExpandedDay] = useState(null);
  const [activeTab, setActiveTab] = useState("plan");

  // If no diet plan, show nothing
  if (!dietPlan) {
    return null;
  }

  // Parse the diet plan if it's a string
  let parsedPlan = dietPlan;
  if (typeof dietPlan === 'string') {
    try {
      parsedPlan = JSON.parse(dietPlan);
    } catch (e) {
      // If it's not JSON, show the raw text
      return (
        <div className="bg-gray-800 p-8 rounded-3xl shadow-xl">
          <h3 className="text-2xl font-bold mb-4 text-green-400">Your Diet Plan</h3>
          <div className="prose prose-invert max-w-none">
            <pre className="whitespace-pre-wrap text-gray-300 text-sm leading-relaxed">
              {dietPlan}
            </pre>
          </div>
        </div>
      );
    }
  }

  const { summary, weekly_plan, guidelines, shopping_list, tips } = parsedPlan;

  // If the structure is not as expected, show raw data
  if (!summary && !weekly_plan) {
    return (
      <div className="bg-gray-800 p-8 rounded-3xl shadow-xl">
        <h3 className="text-2xl font-bold mb-4 text-green-400">Your Diet Plan</h3>
        <div className="prose prose-invert max-w-none">
          <pre className="whitespace-pre-wrap text-gray-300 text-sm leading-relaxed">
            {JSON.stringify(parsedPlan, null, 2)}
          </pre>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto space-y-8">
      {/* Header with Summary - Only show if data exists */}
      {summary && (
        <div className="bg-gradient-to-br from-green-900/20 to-emerald-900/20 backdrop-blur-lg p-8 rounded-3xl shadow-2xl border border-green-500/30">
          <div className="flex items-center gap-3 mb-6">
            <FaAppleAlt className="text-4xl text-green-400" />
            <div>
              <h2 className="text-3xl font-bold text-white">Your Personalized Diet Plan</h2>
              <p className="text-gray-400">Generated by AI based on your profile</p>
            </div>
          </div>

          {/* Nutrition Summary Cards - Only show if data exists */}
          {(summary.total_calories || summary.protein_grams || summary.carbs_grams || summary.fats_grams) && (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
              {summary.total_calories && (
                <NutritionCard
                  icon={<FaFire />}
                  label="Daily Calories"
                  value={summary.total_calories}
                  unit="kcal"
                  color="from-orange-500 to-red-500"
                />
              )}
              {summary.protein_grams && (
                <NutritionCard
                  icon={<FaUtensils />}
                  label="Protein"
                  value={summary.protein_grams}
                  unit="g"
                  color="from-blue-500 to-indigo-500"
                />
              )}
              {summary.carbs_grams && (
                <NutritionCard
                  icon={<FaAppleAlt />}
                  label="Carbs"
                  value={summary.carbs_grams}
                  unit="g"
                  color="from-yellow-500 to-orange-500"
                />
              )}
              {summary.fats_grams && (
                <NutritionCard
                  icon={<FaUtensils />}
                  label="Fats"
                  value={summary.fats_grams}
                  unit="g"
                  color="from-purple-500 to-pink-500"
                />
              )}
            </div>
          )}

          {summary.diet_description && (
            <p className="text-gray-300 bg-gray-900/30 p-4 rounded-xl">
              {summary.diet_description}
            </p>
          )}
        </div>
      )}

      {/* Tab Navigation - Only show if we have content */}
      {(weekly_plan || shopping_list || guidelines || tips) && (
        <div className="flex gap-2 overflow-x-auto pb-2">
          {weekly_plan && weekly_plan.length > 0 && (
            <TabButton
              active={activeTab === "plan"}
              onClick={() => setActiveTab("plan")}
              icon={<FaCalendarAlt />}
              label="Weekly Plan"
            />
          )}
          {shopping_list && shopping_list.length > 0 && (
            <TabButton
              active={activeTab === "shopping"}
              onClick={() => setActiveTab("shopping")}
              icon={<FaShoppingCart />}
              label="Shopping List"
            />
          )}
          {guidelines && guidelines.length > 0 && (
            <TabButton
              active={activeTab === "guidelines"}
              onClick={() => setActiveTab("guidelines")}
              icon={<FaCheck />}
              label="Guidelines"
            />
          )}
          {tips && tips.length > 0 && (
            <TabButton
              active={activeTab === "tips"}
              onClick={() => setActiveTab("tips")}
              icon={<FaLightbulb />}
              label="Tips"
            />
          )}
        </div>
      )}

      {/* Tab Content */}
      {activeTab === "plan" && weekly_plan && weekly_plan.length > 0 && (
        <div className="space-y-4">
          {weekly_plan.map((day, dayIndex) => (
            <DayCard
              key={dayIndex}
              day={day}
              dayIndex={dayIndex}
              expanded={expandedDay === dayIndex}
              onToggle={() => setExpandedDay(expandedDay === dayIndex ? null : dayIndex)}
            />
          ))}
        </div>
      )}

      {activeTab === "shopping" && shopping_list && shopping_list.length > 0 && (
        <div className="bg-gradient-to-br from-gray-800 to-gray-900 p-8 rounded-3xl shadow-2xl border border-gray-700/50">
          <h3 className="text-2xl font-bold mb-6 flex items-center gap-2 text-blue-400">
            <FaShoppingCart /> Shopping List
          </h3>
          <div className="grid md:grid-cols-2 gap-3">
            {shopping_list.map((item, idx) => (
              <div
                key={idx}
                className="bg-gray-900/50 p-4 rounded-xl flex items-center gap-3 hover:bg-gray-800/50 transition-all border border-gray-700/30"
              >
                <div className="w-8 h-8 bg-blue-500/20 rounded-full flex items-center justify-center">
                  <FaCheck className="text-blue-400 text-sm" />
                </div>
                <span className="text-gray-300">{item}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {activeTab === "guidelines" && guidelines && guidelines.length > 0 && (
        <div className="bg-gradient-to-br from-gray-800 to-gray-900 p-8 rounded-3xl shadow-2xl border border-gray-700/50">
          <h3 className="text-2xl font-bold mb-6 flex items-center gap-2 text-green-400">
            <FaCheck /> Important Guidelines
          </h3>
          <div className="space-y-3">
            {guidelines.map((guideline, idx) => (
              <div
                key={idx}
                className="bg-gray-900/50 p-4 rounded-xl flex items-start gap-3 hover:bg-gray-800/50 transition-all border border-gray-700/30"
              >
                <div className="w-6 h-6 bg-green-500/20 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                  <FaCheck className="text-green-400 text-xs" />
                </div>
                <span className="text-gray-300">{guideline}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {activeTab === "tips" && tips && tips.length > 0 && (
        <div className="bg-gradient-to-br from-gray-800 to-gray-900 p-8 rounded-3xl shadow-2xl border border-gray-700/50">
          <h3 className="text-2xl font-bold mb-6 flex items-center gap-2 text-yellow-400">
            <FaLightbulb /> Pro Tips
          </h3>
          <div className="grid md:grid-cols-2 gap-4">
            {tips.map((tip, idx) => (
              <div
                key={idx}
                className="bg-gradient-to-br from-yellow-900/20 to-orange-900/20 p-6 rounded-xl border border-yellow-500/30 hover:border-yellow-500/50 transition-all"
              >
                <div className="flex items-start gap-3">
                  <FaLightbulb className="text-yellow-400 text-xl flex-shrink-0 mt-1" />
                  <p className="text-gray-300">{tip}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// Nutrition Summary Card
function NutritionCard({ icon, label, value, unit, color }) {
  return (
    <div className={`bg-gradient-to-r ${color} p-5 rounded-2xl shadow-lg hover:scale-105 transition-transform`}>
      <div className="flex items-center gap-2 mb-2">
        <div className="text-2xl">{icon}</div>
      </div>
      <div className="text-3xl font-bold mb-1">
        {value}
        <span className="text-lg ml-1">{unit}</span>
      </div>
      <div className="text-sm opacity-90">{label}</div>
    </div>
  );
}

// Tab Button
function TabButton({ active, onClick, icon, label }) {
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-2 px-6 py-3 rounded-xl font-semibold transition-all whitespace-nowrap ${
        active
          ? "bg-gradient-to-r from-green-500 to-emerald-500 text-white shadow-lg"
          : "bg-gray-800 text-gray-300 hover:bg-gray-700"
      }`}
    >
      {icon}
      <span>{label}</span>
    </button>
  );
}

// Day Card Component
function DayCard({ day, dayIndex, expanded, onToggle }) {
  if (!day || !day.meals) return null;

  const totalCalories = day.day_total_calories || 0;

  return (
    <div className="bg-gradient-to-br from-gray-800 to-gray-900 rounded-3xl shadow-2xl border border-gray-700/50 overflow-hidden">
      {/* Day Header */}
      <button
        onClick={onToggle}
        className="w-full p-6 flex justify-between items-center hover:bg-gray-800/50 transition-all"
      >
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 bg-gradient-to-r from-green-500 to-emerald-500 rounded-full flex items-center justify-center font-bold text-xl">
            {dayIndex + 1}
          </div>
          <div className="text-left">
            <h3 className="text-xl font-bold text-white">{day.day || `Day ${dayIndex + 1}`}</h3>
            <p className="text-sm text-gray-400">
              {day.meals.length} meals{totalCalories > 0 && ` • ${totalCalories} kcal`}
            </p>
          </div>
        </div>
        <div className="text-gray-400">
          {expanded ? <FaChevronUp size={24} /> : <FaChevronDown size={24} />}
        </div>
      </button>

      {/* Day Content */}
      {expanded && (
        <div className="p-6 pt-0 space-y-4">
          {day.meals.map((meal, mealIndex) => (
            <MealCard key={mealIndex} meal={meal} />
          ))}

          {/* Hydration Reminder */}
          {day.hydration_reminder && (
            <div className="bg-blue-900/20 p-4 rounded-xl border border-blue-500/30 flex items-center gap-3">
              <div className="text-2xl">💧</div>
              <p className="text-blue-300">{day.hydration_reminder}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// Meal Card Component
function MealCard({ meal }) {
  if (!meal) return null;

  const mealIcons = {
    Breakfast: "🍳",
    "Morning Snack": "🍎",
    Lunch: "🍽️",
    "Evening Snack": "🥤",
    Dinner: "🍲",
  };

  return (
    <div className="bg-gray-900/50 p-5 rounded-xl border border-gray-700/30">
      {/* Meal Header */}
      <div className="flex justify-between items-start mb-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-2xl">{mealIcons[meal.meal_type] || "🍴"}</span>
            <h4 className="text-lg font-bold text-green-400">{meal.meal_type || "Meal"}</h4>
          </div>
          {meal.time && (
            <div className="flex items-center gap-2 text-sm text-gray-400">
              <FaClock className="text-xs" />
              <span>{meal.time}</span>
            </div>
          )}
        </div>
        {meal.total_calories && (
          <div className="text-right">
            <div className="text-2xl font-bold text-orange-400">{meal.total_calories}</div>
            <div className="text-xs text-gray-500">kcal</div>
          </div>
        )}
      </div>

      {/* Food Items */}
      {meal.items && meal.items.length > 0 && (
        <div className="space-y-3">
          {meal.items.map((item, itemIndex) => (
            <div
              key={itemIndex}
              className="bg-gray-800/50 p-4 rounded-lg hover:bg-gray-800/70 transition-all"
            >
              <div className="flex justify-between items-start mb-2">
                <div>
                  <h5 className="font-semibold text-white">{item.name || "Food Item"}</h5>
                  {item.quantity && <p className="text-sm text-gray-400">{item.quantity}</p>}
                </div>
                {item.calories && (
                  <div className="text-right">
                    <div className="font-bold text-orange-300">{item.calories} kcal</div>
                  </div>
                )}
              </div>

              {/* Macros - Only show if data exists */}
              {(item.protein || item.carbs || item.fats) && (
                <div className="flex gap-4 text-xs mt-2">
                  {item.protein && (
                    <div className="flex items-center gap-1">
                      <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                      <span className="text-gray-400">P: {item.protein}g</span>
                    </div>
                  )}
                  {item.carbs && (
                    <div className="flex items-center gap-1">
                      <div className="w-2 h-2 bg-yellow-400 rounded-full"></div>
                      <span className="text-gray-400">C: {item.carbs}g</span>
                    </div>
                  )}
                  {item.fats && (
                    <div className="flex items-center gap-1">
                      <div className="w-2 h-2 bg-purple-400 rounded-full"></div>
                      <span className="text-gray-400">F: {item.fats}g</span>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Meal Notes */}
      {meal.notes && (
        <div className="mt-4 bg-green-900/20 p-3 rounded-lg border border-green-500/30">
          <p className="text-sm text-green-300 flex items-start gap-2">
            <FaLightbulb className="flex-shrink-0 mt-0.5" />
            <span>{meal.notes}</span>
          </p>
        </div>
      )}
    </div>
  );
}